name: 功能请求
description: 提交一个新的功能请求
title: "[Feat] "
labels:
  - enhancement
body:
  - type: checkboxes
    attributes:
      label: 请先使用搜索功能查看该功能是否已被建议过。
      options:
        - label: 我已搜索过重复的 Issue。
          required: true
  - type: textarea
    id: description
    attributes:
      label: 新功能描述
      description: 请详细描述你想要添加的新功能
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: 应用版本
      description: 输入你正在使用的版本
      placeholder: 例如 1.0.0-alpha.1
    validations:
      required: true
